### ISSUE TITLE
Give an example for the \phantom{dummy}

### ISSUE THREAD

**Issue by JocelynDelalande** [fniessen/refcard-org-beamer#4]
Near https://github.com/fniessen/refcard-org-beamer#alternative-environment-syntax-without-option ; I see where it comes from (emacs thread), but cannot figure out how to use that trick.

**Comment by fniessen** [comment]
Sorry for late reply.

Did you try just writing `\phantom{dummy}` instead of leaving the title empty?

In LaTeX (only), `\phantom` inserts an empty box with the same dimensions (horizontal as well as vertical) as the argument.

**Comment by JocelynDelalande** [comment]
@fniessen Ok, I misunderstood it, thanks for clarification.
