### ISSUE TITLE
multiple authors and affiliations

### ISSUE THREAD

**Issue by andreas-h** [fniessen/refcard-org-beamer#5]
Hi, first of all, let me thank for this document, it's very helpful!

Can you elaborate on how to include multiple authors with multiple affiliations?  When I just repeat the `\Institute` command twice, only the second gets printed to the PDF, the first is ignored.

How can I have more than one affiliation?

**Comment by fniessen** [comment]
Hello, glad it's of some use -- for others than just me.

Your question is, in fact, a pure Beamer question; you should first see how to answer it "the Beamer way". Here's one link found by Google: https://tex.stackexchange.com/questions/17961/how-to-add-several-authors-with-different-affiliations-in-beamer.

**Comment by andreas-h** [comment]
Hi, thanks a lot for taking the time to answer :-)

While I agree that it's mostly a LaTeX / Beamer question, using it in Ord doesn't *just work*:

    #+TITLE: Title goes here
    #+AUTHOR: Author1 \inst{1} \and Author2 \inst{2} \and Author3 \inst{3}
    #+LATEX_HEADER: \institute[shortinst]{\inst{1} Affil1 \and \inst{2} Affil2 \and \inst{3} Affil3}
    #+LaTeX_CLASS: beamer
    #+LaTeX_CLASS_OPTIONS: [presentation,smaller]
    #+BEAMER_THEME: default
    
    * First frame
      Hello

doesn't work when I export with `C-C` `C-E` `l` `P`.

The problem seems to be that Org includes the `\inst` in the `pdfauthor` attribute in the call to `\hypersetup`:

    % Created 2017-07-06 Thu 14:01
    % Intended LaTeX compiler: pdflatex
    \documentclass[presentation,smaller]{beamer}
    \usepackage[utf8]{inputenc}
    \usepackage[T1]{fontenc}
    \usepackage{graphicx}
    \usepackage{grffile}
    \usepackage{longtable}
    \usepackage{wrapfig}
    \usepackage{rotating}
    \usepackage[normalem]{ulem}
    \usepackage{amsmath}
    \usepackage{textcomp}
    \usepackage{amssymb}
    \usepackage{capt-of}
    \usepackage{hyperref}
    \usepackage{graphicx}
    \usepackage{longtable}
    \usepackage{float}
    \institute[shortinst]{\inst{1} Affil1 \and \inst{2} Affil2 \and \inst{3} Affil3}
    \usetheme{default}
    \author{Author1 \inst{1} \and Author2 \inst{2} \and Author3 \inst{3}}
    \date{\today}
    \title{Title goes here}
    \hypersetup{
     pdfauthor={Author1 \inst{1} \and Author2 \inst{2} \and Author3 \inst{3}},
     pdftitle={Title goes here},
     pdfkeywords={},
     pdfsubject={},
     pdfcreator={Emacs 25.1.1 (Org mode 9.0.9)}, 
     pdflang={English}}
    \begin{document}
    
    \maketitle
    \begin{frame}{Outline}
    \tableofcontents
    \end{frame}
    
    
    \begin{frame}[label={sec:orga8a4e3d}]{First frame}
    Hello
    \end{frame}
    \end{document}

When I remove the `\hypersetup` command, I can compile the resulting TeX without problems.
